repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.289
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args:
          - --fix
          - --target-version=py311
          - --select=B,C,E,F,W,D
          - --line-length=80
          - --config=pyproject.toml

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args:
          - --safe
          - --target-version=py312
          - --line-length=80