name: Format-and-Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ${{ env.CONDA_ENV }}
          python-version: "3.12"
          channels: conda-forge,defaults
      - name: Install dependencies
        run: |
          conda install -c conda-forge pre-commit ruff black -y
      - name: Run pre-commit
        run: |
          pre-commit run --all-files